name: Blog in Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * FRI'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://nkupp.com/atom.xml
